### ISSUE TITLE
MiningLocations error

### ISSUE THREAD

**Issue by Andyauk** [trclassic92/tr-mining#1]
[    script:tr-mining] SCRIPT ERROR: @tr-mining/server/main.lua:136: bad argument #1 to 'pairs' (table expected, got nil)
[    script:tr-mining] > fn (@tr-mining/server/main.lua:136)

not noticed this before, but felt I would post it. 
I don't tend to go in all of the mine, just the top. but today I went all the way in and got this message. not sure if it was when the message comes up to say something is near by, as it didn't go away.  its so dark in there lol

**Comment by trclassic92** [comment]
I will take a look at this
