### ISSUE TITLE
female cant wash the stones.

### ISSUE THREAD

**Issue by Andyauk** [trclassic92/tr-mining#3]
females cant wash the stones.?

**Comment by trclassic92** [comment]
> 

All peds should be able to wash stones.. What happens when a female ped trys to?

**Comment by Andyauk** [comment]
> > 
> 
> All peds should be able to wash stones.. What happens when a female ped trys to?

they just stand there.

**Comment by trclassic92** [comment]
Can you show me a video of it happening cause I can't recreate it.

**Comment by Andyauk** [comment]
> Can you show me a video of it happening cause I can't recreate it.

Ok, I'll get it to you asap
