### ISSUE TITLE
mine everywhere

### ISSUE THREAD

**Issue by DeadWorld3113** [trclassic92/tr-mining#5]
when you go over a minning point and you exit no matter where you are on the map when you press E it will start mining

**Comment by trclassic92** [comment]
> when you go over a minning point and you exit no matter where you are on the map when you press E it will start mining

Do you have a video you can add to this issue so I can see exactly what is happening?

**Comment by LYRYCAL** [comment]
> > when you go over a minning point and you exit no matter where you are on the map when you press E it will start mining
> 
> Do you have a video you can add to this issue so I can see exactly what is happening?

the problem looks similar like this one mate [zone check](https://github.com/qbcore-framework/qb-shops/pull/82)

**Comment by trclassic92** [comment]
Fixed

**Comment by DeadWorld3113** [comment]
Perfect Nice Job !
